-- Knowledge base for the AI Coach RAG. embedding is backfilled once by embedKnowledge().
insert into public.knowledge_base (category, title, content, tags) values
('programming', 'Progressive overload adalah kunci',
  'Otot tumbuh saat diberi beban yang meningkat secara bertahap. Tambah beban, repetisi, atau set sedikit demi sedikit setiap minggu. Jika kamu bisa menyelesaikan semua set di ujung atas rentang repetisi dengan teknik baik, naikkan beban ~2.5kg untuk barbel atau 1-2kg untuk dumbbell pada sesi berikutnya.', '{overload,progres,beban}'),
('programming', 'Pilih split sesuai frekuensi',
  '2-3 hari/minggu paling efektif dengan full-body. 4 hari cocok untuk upper/lower. 5-6 hari ideal untuk push/pull/legs. Lebih penting konsisten 3 hari daripada merencanakan 6 hari tapi bolong.', '{split,frekuensi,jadwal}'),
('technique', 'Teknik squat yang aman',
  'Jaga punggung netral, dada tegak, dan tekuk dari pinggul lebih dulu. Lutut mengikuti arah jari kaki, jangan jatuh ke dalam. Jika lutut sakit, periksa kedalaman, lebar kaki, dan kontrol turunnya; kurangi beban dan perlambat gerakan.', '{squat,lutut,teknik}'),
('technique', 'Hindari cedera punggung saat hinge',
  'Pada deadlift/RDL, gerakan berasal dari pinggul, bukan membungkukkan punggung. Jaga bar dekat tubuh, core terkunci, dan punggung lurus. Nyeri punggung bawah biasanya tanda beban terlalu berat atau pinggul kurang dipakai.', '{deadlift,rdl,punggung_bawah}'),
('nutrition', 'Kalori dan protein menentukan hasil',
  '70-80% hasil ditentukan total kalori harian, protein, dan tidur — bukan satu suplemen. Untuk menurunkan lemak, makan sedikit di bawah TDEE. Untuk menambah otot, makan sedikit di atas TDEE. Target protein 1.6-2.2 g per kg berat badan.', '{kalori,protein,tdee}'),
('nutrition', 'Sumber protein murah dan lokal',
  'Telur, dada ayam, tahu, tempe, ikan kembung, dan ikan lele adalah sumber protein murah dan mudah didapat di Indonesia. Susu/whey hanya pelengkap praktis, bukan penentu hasil. Utamakan makanan utuh dulu.', '{protein,makanan,murah,whey}'),
('nutrition', 'Mitos cewek angkat beban jadi bulky',
  'Latihan beban tidak membuat perempuan jadi besar/bulky. Perempuan memiliki testosteron jauh lebih rendah sehingga sulit membentuk massa otot besar. Latihan beban justru mengencangkan tubuh, membakar lemak, dan menguatkan tulang.', '{cewek,bulky,mitos,toning}'),
('recovery', 'Tidur dan istirahat membangun otot',
  'Otot tumbuh saat istirahat, bukan saat latihan. Tidur 7-9 jam dan beri jeda 48 jam untuk kelompok otot yang sama. Jika lelah berlebihan, nyeri sendi, atau performa turun, ambil deload atau hari istirahat tambahan.', '{tidur,istirahat,recovery,deload}'),
('motivation', 'Konsistensi mengalahkan kesempurnaan',
  'Hasil datang dari kebiasaan kecil yang dijaga lama. Lebih baik latihan singkat tapi rutin daripada program ambisius yang berhenti dalam dua minggu. Rayakan streak dan target mingguan kecil agar tetap termotivasi.', '{konsisten,streak,motivasi}'),
('motivation', 'Saat malas, perkecil targetnya',
  'Saat tidak ada mood, jangan batalkan total. Datang dan lakukan versi mini sesi (1-2 gerakan inti). Memulai biasanya cukup untuk membangun momentum, dan menjaga streak tetap hidup lebih berharga daripada satu sesi sempurna.', '{malas,mood,kebiasaan}'),
('safety', 'Kapan harus konsultasi tenaga medis',
  'Aplikasi memberi panduan umum, bukan nasihat medis. Jika ada nyeri tajam, cedera lama yang kambuh, pusing, atau kondisi kesehatan tertentu, hentikan dan konsultasikan ke dokter atau fisioterapis sebelum melanjutkan.', '{cedera,medis,disclaimer,aman}');
