-- ══════════════════════════════════════════════════════════════
-- 016 — Seed exercise BARU (menggantikan 015 + batch tambahan 65 gerakan).
-- Cek dulu slug/variation_group yang sudah ada di 010/012/014 (lihat EXERCISES.md)
-- agar tidak bentrok. Sumber video: hasil scraping (isi via browser-act, dll).
-- on conflict (slug) do nothing → aman kalau dijalankan ulang.
-- Setelah migrate: jalankan embedExercises() untuk backfill embedding.
-- ══════════════════════════════════════════════════════════════

-- Vocabulary valid (WAJIB konsisten):
-- muscle_group : legs | chest | back | shoulders | arms | core | full_body
-- movement_pattern : squat | hinge | push_horizontal | push_vertical |
-- pull_horizontal | pull_vertical | isolation_biceps |
-- isolation_triceps | isolation_chest | isolation_back |
-- isolation_legs | calf | core | cardio
-- category : compound | isolation | cardio
-- equipment : barbell | dumbbell | machine | bodyweight | cardio
-- level : pemula | menengah | mahir
-- injury_cautions : lutut | punggung_bawah | bahu | siku |
-- pergelangan_tangan | pergelangan_kaki
-- Kolom yang TIDAK diisi: id (auto), embedding (null → backfill), created_at (default).

-- Goals pada aplikasi ini:
--   turun_lemak, naik_massa, toning, strength, kebugaran_umum, kesuburan
-- CATATAN: seed ini SUDAH dijalankan ke DB (2026-07-04) via script dengan
-- dedup slug+nama — 65 baris masuk, 37 duplikat dilewati.

/\* data lama — 45 gerakan existing (010 + 012 + 014). JANGAN pakai ulang slug ini.
Format: slug (equipment · level · variation_group)

SQUAT
barbell-back-squat (barbell · menengah · squat)
goblet-squat (dumbbell · pemula · squat)
bodyweight-squat (bodyweight · pemula · squat)
deep-squat-hold (bodyweight · pemula · squat) [012]
bulgarian-split-squat (bodyweight · menengah · squat) [014]
dumbbell-front-squat (dumbbell · menengah · squat) [014]
squat-jump (bodyweight · menengah · squat) [014]

HINGE
barbell-rdl (barbell · menengah · hinge)
dumbbell-rdl (dumbbell · pemula · hinge)
glute-bridge (bodyweight · pemula · hinge)
hip-thrust (bodyweight · pemula · hinge) [012]
single-leg-rdl (bodyweight · menengah · hinge) [014]

PUSH_HORIZONTAL
barbell-bench-press (barbell · menengah · push_horizontal)
dumbbell-bench-press (dumbbell · pemula · push_horizontal)
push-up (bodyweight · pemula · push_horizontal)

PUSH_VERTICAL
barbell-overhead-press (barbell · menengah · push_vertical)
dumbbell-shoulder-press(dumbbell · pemula · push_vertical)
pike-push-up (bodyweight · menengah · push_vertical)

PULL_VERTICAL
lat-pulldown (machine · pemula · pull_vertical)
pull-up (bodyweight · menengah · pull_vertical)

PULL_HORIZONTAL
barbell-row (barbell · menengah · pull_horizontal)
dumbbell-row (dumbbell · pemula · pull_horizontal)
inverted-row (bodyweight · pemula · pull_horizontal)
renegade-row (dumbbell · menengah · pull_horizontal) [014]

ISOLATION_BICEPS
dumbbell-bicep-curl (dumbbell · pemula · isolation_biceps)
ISOLATION_TRICEPS
triceps-dip-bench (bodyweight · pemula · isolation_triceps)
ISOLATION_CHEST
dumbbell-chest-fly (dumbbell · pemula · isolation_chest)
ISOLATION_BACK
dumbbell-rear-delt-fly (dumbbell · pemula · isolation_back)

ISOLATION_LEGS
walking-lunge (bodyweight · pemula · isolation_legs)
reverse-lunge (bodyweight · pemula · isolation_legs) [014]
step-up (bodyweight · pemula · isolation_legs) [014]

CALF
calf-raise (bodyweight · pemula · calf)

CORE
plank (bodyweight · pemula · core)
pelvic-floor-kegel (bodyweight · pemula · core) [012]
bird-dog (bodyweight · pemula · core) [012]
dead-bug (bodyweight · pemula · core) [012]
cat-cow (bodyweight · pemula · core) [012]
side-plank (bodyweight · pemula · core) [014]
superman (bodyweight · pemula · core) [014]
plank-shoulder-tap (bodyweight · pemula · core) [014]
bear-crawl-hold (bodyweight · pemula · core) [014]
suitcase-hold (dumbbell · pemula · core) [014]
copenhagen-side-plank (bodyweight · mahir · core) [014]

CARDIO
jump-rope (bodyweight · pemula · cardio)
brisk-walk (bodyweight · pemula · cardio) [012]
\*/

insert into public.exercises
(slug, name, name_id, muscle_group, secondary_muscles, movement_pattern,
category, equipment, level, is_compound, technique_steps, injury_cautions,
variation_group, video_url)
values
-- ══ STRENGTH / NAIK MASSA — barbell & machine compound ══
('conventional-deadlift', 'Deadlift', 'Deadlift Konvensional',
 'legs', '{glutes,back,core}', 'hinge', 'compound', 'barbell', 'menengah', true,
 ARRAY['Berdiri kaki selebar pinggul, barbel di atas tengah telapak kaki.','Tekuk pinggul dan lutut, genggam bar selebar bahu, dada tegak punggung netral.','Dorong lantai dengan kaki sambil mengangkat bar rapat ke tubuh hingga berdiri tegak.','Turunkan bar terkontrol dengan pola hinge, jaga punggung tetap lurus.'],
 '{punggung_bawah}', 'hinge', 'https://www.youtube.com/watch?v=XxWcirHIwVo'),
('sumo-deadlift', 'Sumo Deadlift', 'Deadlift Sumo',
 'legs', '{glutes,back,core}', 'hinge', 'compound', 'barbell', 'menengah', true,
 ARRAY['Ambil kuda-kuda lebar, ujung kaki mengarah keluar, tangan menggenggam bar di dalam kaki.','Turunkan pinggul, dada tegak, punggung netral, bahu di atas bar.','Dorong lantai dan buka pinggul untuk mengangkat bar hingga berdiri tegak.','Turunkan bar terkontrol menjaga punggung lurus.'],
 '{punggung_bawah}', 'hinge', 'https://www.youtube.com/watch?v=JbY72Him34Q'),
('barbell-front-squat', 'Barbell Front Squat', 'Front Squat Barbel',
 'legs', '{glutes,core}', 'squat', 'compound', 'barbell', 'menengah', true,
 ARRAY['Letakkan bar di depan bahu, siku tinggi sejajar lantai.','Berdiri kaki selebar bahu, jaga dada dan siku tetap terangkat.','Turun jongkok dengan mendorong pinggul ke belakang hingga paha sejajar lantai.','Dorong lantai untuk kembali berdiri, tumit tetap menapak.'],
 '{lutut,pergelangan_tangan}', 'squat', 'https://www.youtube.com/watch?v=v-mQm_droHg'),
('barbell-hip-thrust', 'Barbell Hip Thrust', 'Hip Thrust Barbel',
 'legs', '{glutes,core}', 'hinge', 'compound', 'barbell', 'menengah', true,
 ARRAY['Sandarkan punggung atas pada bangku, bar berlapis busa di lipatan pinggul.','Tekuk lutut, telapak kaki menapak penuh selebar pinggul.','Dorong pinggul ke atas hingga badan sejajar dari lutut ke bahu, remas glutes.','Turunkan pinggul terkontrol tanpa melengkungkan punggung bawah.'],
 '{punggung_bawah}', 'hinge', 'https://www.youtube.com/watch?v=SEdqd1n0cvg'),
('leg-press', 'Leg Press', 'Leg Press',
 'legs', '{glutes}', 'squat', 'compound', 'machine', 'pemula', true,
 ARRAY['Duduk di mesin, telapak kaki di platform selebar bahu.','Lepas pengaman, turunkan platform hingga lutut membentuk sekitar 90 derajat.','Dorong platform menjauh tanpa mengunci lutut sepenuhnya.','Jaga punggung bawah menempel pada sandaran sepanjang gerakan.'],
 '{lutut}', 'squat', 'https://www.youtube.com/watch?v=K5n2vg3oZa4'),
('hack-squat', 'Hack Squat', 'Hack Squat',
 'legs', '{glutes}', 'squat', 'compound', 'machine', 'menengah', true,
 ARRAY['Posisikan bahu di bawah bantalan, punggung menempel sandaran.','Kaki selebar bahu di platform, lepas pengaman.','Turun jongkok terkontrol hingga paha sejajar lantai.','Dorong kembali ke atas melalui tumit tanpa mengunci lutut keras.'],
 '{lutut}', 'squat', 'https://www.youtube.com/watch?v=rYgNArpwE7E'),
-- ══ PUSH ══
('incline-dumbbell-press', 'Incline Dumbbell Press', 'Incline Dumbbell Press',
 'chest', '{shoulders,arms}', 'push_horizontal', 'compound', 'dumbbell', 'pemula', true,
 ARRAY['Atur bangku pada kemiringan sekitar 30 derajat.','Pegang dumbbell setinggi dada, pergelangan tangan lurus.','Dorong dumbbell ke atas hingga lengan hampir lurus.','Turunkan terkontrol hingga terasa regangan di dada.'],
 '{bahu}', 'push_horizontal', 'https://www.youtube.com/watch?v=IP4oeKh1Sd4'),
('chest-press-machine', 'Machine Chest Press', 'Chest Press Mesin',
 'chest', '{shoulders,arms}', 'push_horizontal', 'compound', 'machine', 'pemula', true,
 ARRAY['Atur tinggi kursi agar pegangan sejajar tengah dada.','Punggung menempel sandaran, genggam pegangan.','Dorong pegangan ke depan hingga lengan hampir lurus.','Kembalikan terkontrol tanpa membenturkan beban.'],
 '{bahu}', 'push_horizontal', 'https://www.youtube.com/watch?v=sqNwDkUU_Ps'),
('chest-dip', 'Chest Dip', 'Dip Dada',
 'chest', '{arms,shoulders}', 'push_horizontal', 'compound', 'bodyweight', 'menengah', true,
 ARRAY['Naik ke palang paralel, lengan lurus menopang tubuh.','Condongkan badan sedikit ke depan untuk menargetkan dada.','Turun terkontrol hingga siku sekitar 90 derajat.','Dorong kembali ke atas hingga lengan lurus.'],
 '{bahu}', 'push_horizontal', 'https://www.youtube.com/watch?v=yN6Q1UI_xkE'),
('arnold-press', 'Arnold Press', 'Arnold Press',
 'shoulders', '{arms}', 'push_vertical', 'compound', 'dumbbell', 'menengah', true,
 ARRAY['Duduk tegak, mulai dengan dumbbell di depan bahu telapak menghadap tubuh.','Saat mendorong ke atas, putar pergelangan sehingga telapak menghadap depan.','Luruskan lengan di atas kepala tanpa mengunci keras.','Turunkan sambil memutar kembali ke posisi awal.'],
 '{bahu}', 'push_vertical', 'https://www.youtube.com/watch?v=ris9tKqMwgU'),
('machine-shoulder-press', 'Machine Shoulder Press', 'Shoulder Press Mesin',
 'shoulders', '{arms}', 'push_vertical', 'compound', 'machine', 'pemula', true,
 ARRAY['Atur kursi agar pegangan setinggi bahu.','Punggung menempel sandaran, genggam pegangan.','Dorong ke atas hingga lengan hampir lurus.','Turunkan terkontrol hingga setinggi bahu.'],
 '{bahu}', 'push_vertical', 'https://www.youtube.com/watch?v=3R14MnZbcpw'),
-- ══ PULL ══
('seated-cable-row', 'Seated Cable Row', 'Seated Cable Row',
 'back', '{arms,shoulders}', 'pull_horizontal', 'compound', 'machine', 'pemula', true,
 ARRAY['Duduk dengan lutut sedikit menekuk, pegang gagang, dada tegak.','Tarik gagang ke arah perut sambil meremas tulang belikat.','Jaga punggung tetap netral, jangan mengayun.','Ulur lengan kembali terkontrol menjaga postur tegak.'],
 '{punggung_bawah}', 'pull_horizontal', 'https://www.youtube.com/watch?v=vwHG9Jfu4sw'),
('t-bar-row', 'T-Bar Row', 'T-Bar Row',
 'back', '{arms,shoulders}', 'pull_horizontal', 'compound', 'barbell', 'menengah', true,
 ARRAY['Berdiri mengangkang bar, pinggul menekuk sekitar 45 derajat, punggung netral.','Genggam gagang, tarik bar ke arah dada bawah.','Remas punggung di puncak gerakan.','Turunkan terkontrol menjaga punggung tetap lurus.'],
 '{punggung_bawah}', 'pull_horizontal', 'https://www.youtube.com/watch?v=TyLoy3n_a10'),
('chin-up', 'Chin-Up', 'Chin-Up',
 'back', '{arms}', 'pull_vertical', 'compound', 'bodyweight', 'menengah', true,
 ARRAY['Gantung pada palang dengan pegangan selebar bahu telapak menghadap tubuh.','Tarik tubuh ke atas hingga dagu melewati palang.','Remas otot punggung dan bisep di puncak.','Turun terkontrol hingga lengan lurus penuh.'],
 '{bahu,siku}', 'pull_vertical', 'https://www.youtube.com/watch?v=e1YSApl-QcM'),
('face-pull', 'Face Pull', 'Face Pull',
 'shoulders', '{back}', 'isolation_back', 'isolation', 'machine', 'pemula', false,
 ARRAY['Atur katrol setinggi wajah dengan tali.','Tarik tali ke arah wajah, siku tinggi dan melebar.','Remas rear delt dan otot punggung atas.','Kembalikan terkontrol tanpa mengangkat bahu.'],
 '{bahu}', 'isolation_back', 'https://www.youtube.com/watch?v=eTCBSFlCJ_s'),
('dumbbell-shrug', 'Dumbbell Shrug', 'Shrug Dumbbell',
 'back', '{shoulders}', 'isolation_back', 'isolation', 'dumbbell', 'pemula', false,
 ARRAY['Berdiri tegak memegang dumbbell di samping tubuh.','Angkat bahu lurus ke atas ke arah telinga.','Tahan sebentar di puncak lalu turunkan terkontrol.','Hindari memutar bahu.'],
 '{}', 'isolation_back', 'https://www.youtube.com/watch?v=cJRVVxmytaM'),
-- ══ TONING / NAIK MASSA — isolasi lengan, kaki, dada, bahu, betis ══
('hammer-curl', 'Hammer Curl', 'Hammer Curl',
 'arms', '{}', 'isolation_biceps', 'isolation', 'dumbbell', 'pemula', false,
 ARRAY['Berdiri memegang dumbbell dengan telapak saling menghadap.','Tekuk siku mengangkat dumbbell menjaga pergelangan netral.','Remas bisep di puncak.','Turunkan terkontrol tanpa mengayun badan.'],
 '{siku}', 'isolation_biceps', 'https://www.youtube.com/watch?v=OPqe0kCxmR8'),
('barbell-curl', 'Barbell Biceps Curl', 'Barbell Curl',
 'arms', '{}', 'isolation_biceps', 'isolation', 'barbell', 'pemula', false,
 ARRAY['Berdiri memegang barbel selebar bahu, telapak menghadap depan.','Tekuk siku mengangkat bar ke arah dada.','Jaga siku tetap dekat tubuh, jangan mengayun.','Turunkan terkontrol hingga lengan lurus.'],
 '{siku}', 'isolation_biceps', 'https://www.youtube.com/watch?v=ZQWL7omZh94'),
('triceps-pushdown', 'Triceps Pushdown', 'Triceps Pushdown',
 'arms', '{}', 'isolation_triceps', 'isolation', 'machine', 'pemula', false,
 ARRAY['Berdiri menghadap katrol tinggi, genggam gagang.','Jaga siku menempel di sisi tubuh.','Luruskan lengan ke bawah hingga penuh, remas trisep.','Kembalikan terkontrol tanpa menggerakkan siku.'],
 '{siku}', 'isolation_triceps', 'https://www.youtube.com/watch?v=-zLyUAo1gMw'),
('overhead-triceps-extension', 'Overhead Triceps Extension', 'Overhead Triceps Extension',
 'arms', '{}', 'isolation_triceps', 'isolation', 'dumbbell', 'pemula', false,
 ARRAY['Pegang satu dumbbell dengan dua tangan di atas kepala.','Jaga siku mengarah ke depan dan dekat kepala.','Turunkan dumbbell ke belakang kepala dengan menekuk siku.','Luruskan kembali lengan ke atas, remas trisep.'],
 '{siku}', 'isolation_triceps', 'https://www.youtube.com/watch?v=fYqswDVbJDg'),
('skull-crusher', 'Skull Crusher', 'Skull Crusher',
 'arms', '{}', 'isolation_triceps', 'isolation', 'barbell', 'menengah', false,
 ARRAY['Berbaring di bangku, pegang barbel di atas dada lengan lurus.','Tekuk siku menurunkan bar ke arah dahi.','Jaga lengan atas tetap diam.','Luruskan kembali lengan ke posisi awal.'],
 '{siku}', 'isolation_triceps', 'https://www.youtube.com/watch?v=RavQHfFxbdA'),
('leg-extension', 'Leg Extension', 'Leg Extension',
 'legs', '{}', 'isolation_legs', 'isolation', 'machine', 'pemula', false,
 ARRAY['Duduk di mesin, sandaran kaki di atas pergelangan.','Luruskan lutut mengangkat beban hingga kaki hampir lurus.','Remas paha depan di puncak.','Turunkan terkontrol tanpa membanting beban.'],
 '{lutut}', 'isolation_legs', 'https://www.youtube.com/watch?v=swZQC689o9U'),
('lying-leg-curl', 'Lying Leg Curl', 'Lying Leg Curl',
 'legs', '{}', 'isolation_legs', 'isolation', 'machine', 'pemula', false,
 ARRAY['Telungkup di mesin, bantalan di atas tumit belakang.','Tekuk lutut menarik tumit ke arah bokong.','Remas hamstring di puncak.','Turunkan terkontrol.'],
 '{lutut}', 'isolation_legs', 'https://www.youtube.com/watch?v=q1cKTmaeQWo'),
('hip-abduction-machine', 'Hip Abduction Machine', 'Hip Abduction Mesin',
 'legs', '{glutes}', 'isolation_legs', 'isolation', 'machine', 'pemula', false,
 ARRAY['Duduk di mesin, sisi luar paha menempel bantalan.','Buka kedua kaki melawan tahanan.','Tahan sebentar di posisi terbuka.','Kembalikan terkontrol.'],
 '{}', 'isolation_legs', 'https://www.youtube.com/watch?v=h9BqUMqK-SY'),
('cable-crossover', 'Cable Crossover', 'Cable Crossover',
 'chest', '{shoulders}', 'isolation_chest', 'isolation', 'machine', 'menengah', false,
 ARRAY['Atur katrol tinggi, pegang gagang di kedua sisi, melangkah ke depan.','Sedikit condong ke depan, siku agak menekuk.','Bawa kedua tangan ke tengah di depan dada.','Kembalikan terkontrol merasakan regangan dada.'],
 '{bahu}', 'isolation_chest', 'https://www.youtube.com/watch?v=JUDTGZh4rhg'),
('dumbbell-lateral-raise', 'Lateral Raise', 'Lateral Raise',
 'shoulders', '{}', 'push_vertical', 'isolation', 'dumbbell', 'pemula', false,
 ARRAY['Berdiri memegang dumbbell di samping tubuh.','Angkat lengan ke samping hingga setinggi bahu, siku sedikit menekuk.','Jaga bahu tetap turun, jangan mengangkat trapezius.','Turunkan terkontrol.'],
 '{bahu}', 'push_vertical', 'https://www.youtube.com/watch?v=PzsMitRdI_8'),
('seated-calf-raise', 'Seated Calf Raise', 'Seated Calf Raise',
 'legs', '{}', 'calf', 'isolation', 'machine', 'pemula', false,
 ARRAY['Duduk dengan bantalan di atas paha, ujung kaki di pijakan.','Turunkan tumit hingga terasa regangan betis.','Angkat tumit setinggi mungkin, remas betis.','Turunkan terkontrol.'],
 '{pergelangan_kaki}', 'calf', 'https://www.youtube.com/watch?v=6O5hh1rBtx8'),
-- ══ TURUN LEMAK / KEBUGARAN UMUM — cardio & conditioning ══
('burpee', 'Burpee', 'Burpee',
 'full_body', '{legs,chest,core}', 'cardio', 'cardio', 'bodyweight', 'menengah', false,
 ARRAY['Mulai berdiri, lalu jongkok dan letakkan telapak tangan di lantai.','Lempar kaki ke belakang ke posisi plank.','Tarik kaki kembali ke jongkok.','Lompat tegak ke atas, ulangi berirama.'],
 '{punggung_bawah,pergelangan_tangan}', 'cardio', 'https://www.youtube.com/watch?v=G2hv_NYhM-A'),
('mountain-climber', 'Mountain Climber', 'Mountain Climber',
 'full_body', '{core,shoulders}', 'cardio', 'cardio', 'bodyweight', 'pemula', false,
 ARRAY['Mulai posisi plank tinggi, tubuh lurus.','Tarik satu lutut ke arah dada.','Ganti kaki dengan cepat seperti berlari di tempat.','Jaga pinggul tetap rendah dan inti aktif.'],
 '{pergelangan_tangan}', 'cardio', 'https://www.youtube.com/watch?v=cnyTQDSE884'),
('jumping-jack', 'Jumping Jack', 'Jumping Jack',
 'full_body', '{legs}', 'cardio', 'cardio', 'bodyweight', 'pemula', false,
 ARRAY['Berdiri tegak, kaki rapat, tangan di samping.','Lompat membuka kaki sambil mengangkat tangan ke atas kepala.','Lompat kembali ke posisi awal.','Pertahankan irama yang stabil.'],
 '{pergelangan_kaki}', 'cardio', 'https://www.youtube.com/watch?v=XR0xeuK5zBU'),
('kettlebell-swing', 'Kettlebell Swing', 'Kettlebell Swing',
 'full_body', '{glutes,back,core}', 'hinge', 'compound', 'dumbbell', 'menengah', true,
 ARRAY['Berdiri kaki selebar bahu, beban di depan, pola hinge pinggul.','Ayun beban ke belakang di antara kaki.','Dorong pinggul ke depan eksplosif mengayun beban setinggi dada.','Biarkan beban turun kembali dengan hinge, jaga punggung netral.'],
 '{punggung_bawah}', 'hinge', 'https://www.youtube.com/watch?v=sSESeQAir2M'),
('rowing-machine', 'Rowing Machine', 'Mesin Rowing',
 'full_body', '{back,legs,arms}', 'cardio', 'cardio', 'cardio', 'pemula', false,
 ARRAY['Duduk, ikat kaki, pegang gagang, mulai posisi catch lutut menekuk.','Dorong dengan kaki lebih dulu.','Lanjutkan dengan mencondong badan sedikit dan tarik gagang ke tulang rusuk bawah.','Kembali dengan urutan terbalik: lengan, badan, lalu lutut.'],
 '{punggung_bawah}', 'cardio', 'https://www.youtube.com/watch?v=ZN0J6qKCIrI'),
('stationary-bike', 'Stationary Bike', 'Sepeda Statis',
 'legs', '{glutes}', 'cardio', 'cardio', 'cardio', 'pemula', false,
 ARRAY['Atur tinggi sadel agar lutut sedikit menekuk saat pedal terbawah.','Pegang setang dengan rileks, punggung netral.','Kayuh dengan irama stabil sesuai intensitas target.','Jaga pergerakan lutut lurus ke depan.'],
 '{}', 'cardio', 'https://www.youtube.com/watch?v=gWosN1CY4bg'),
('elliptical-trainer', 'Elliptical Trainer', 'Elliptical',
 'full_body', '{legs}', 'cardio', 'cardio', 'cardio', 'pemula', false,
 ARRAY['Berdiri tegak, telapak kaki penuh di pijakan, pegang pegangan.','Gerakkan kaki dengan pola elips halus.','Libatkan tangan mendorong dan menarik pegangan.','Jaga postur tegak, inti aktif.'],
 '{}', 'cardio', 'https://www.youtube.com/watch?v=EesEvYohy5o'),
-- ══ KESUBURAN / MOBILITAS & PEMULIHAN — intensitas ringan, aktivasi inti & panggul ══
('glute-bridge-march', 'Glute Bridge March', 'Glute Bridge March',
 'core', '{glutes}', 'core', 'isolation', 'bodyweight', 'pemula', false,
 ARRAY['Berbaring telentang, lutut menekuk, telapak menapak lantai.','Angkat pinggul membentuk garis lurus bahu ke lutut.','Sambil pinggul tetap terangkat, angkat satu lutut ke arah dada bergantian.','Jaga pinggul stabil tidak miring, inti aktif.'],
 '{punggung_bawah}', 'core', 'https://www.youtube.com/watch?v=KsYwYl13IDc'),
('diaphragmatic-breathing', 'Diaphragmatic Breathing', 'Napas Diafragma',
 'core', '{}', 'core', 'isolation', 'bodyweight', 'pemula', false,
 ARRAY['Berbaring atau duduk nyaman, satu tangan di dada satu di perut.','Tarik napas lewat hidung mengembangkan perut, dada tetap diam.','Hembuskan perlahan lewat mulut mengempiskan perut.','Ulangi ritmis untuk relaksasi dan aktivasi inti dalam.'],
 '{}', 'core', 'https://www.youtube.com/watch?v=9jpchJcKivk'),
('world-greatest-stretch', 'Worlds Greatest Stretch', 'Peregangan Dinamis Menyeluruh',
 'full_body', '{legs,core}', 'core', 'isolation', 'bodyweight', 'pemula', false,
 ARRAY['Mulai posisi lunge depan dengan kaki depan menapak penuh.','Letakkan tangan di dalam kaki depan, turunkan siku ke arah lantai.','Putar dada membuka ke atas mengangkat satu tangan ke langit.','Kembali dan ganti sisi, gerakan halus terkontrol.'],
 '{}', 'core', 'https://www.youtube.com/watch?v=-CiWQ2IvY34'),
-- ══ BATCH TAMBAHAN — variasi pemula/menengah/mahir (65 gerakan, video via browser-act stealth) ══
('box-squat', 'Box Squat', 'Box Squat',
 'legs', '{glutes,core}', 'squat',
 'compound', 'barbell', 'menengah', true,
 ARRAY['Berdiri di depan box setinggi lutut, bar di punggung atas.','Dorong pinggul ke belakang dan turun terkontrol hingga duduk ringan di box.','Jeda sesaat tanpa melepas ketegangan otot.','Dorong lantai untuk berdiri kembali, dada tetap tegak.'],
 '{lutut,punggung_bawah}', 'squat', 'https://www.youtube.com/watch?v=rRihE4weYg4'),
('overhead-squat', 'Overhead Squat', 'Overhead Squat',
 'legs', '{shoulders,core}', 'squat',
 'compound', 'barbell', 'mahir', true,
 ARRAY['Pegang bar lebar di atas kepala, lengan terkunci lurus.','Kaki selebar bahu, dada tegak, inti aktif.','Turun jongkok dalam sambil menjaga bar stabil di atas kepala.','Dorong berdiri kembali tanpa bar bergeser ke depan.'],
 '{bahu,punggung_bawah,lutut}', 'squat', 'https://www.youtube.com/watch?v=BYi-TBOtNTo'),
('pistol-squat', 'Pistol Squat', 'Pistol Squat',
 'legs', '{glutes,core}', 'squat',
 'compound', 'bodyweight', 'mahir', true,
 ARRAY['Berdiri satu kaki, kaki lain lurus ke depan.','Rentangkan tangan ke depan sebagai penyeimbang.','Turun jongkok penuh pada satu kaki terkontrol.','Dorong kembali berdiri tanpa kaki bantu menyentuh lantai.'],
 '{lutut,pergelangan_kaki}', 'squat', 'https://www.youtube.com/watch?v=bH3mRwnAN88'),
('wall-sit', 'Wall Sit', 'Wall Sit',
 'legs', '{glutes}', 'squat',
 'compound', 'bodyweight', 'pemula', true,
 ARRAY['Sandarkan punggung rata pada dinding.','Turun hingga paha sejajar lantai, lutut 90 derajat.','Tahan posisi, punggung tetap menempel dinding.','Bernapas normal selama durasi target.'],
 '{lutut}', 'squat', 'https://www.youtube.com/watch?v=cWTZ8Am1Ee0'),
('smith-machine-squat', 'Smith Machine Squat', 'Squat Mesin Smith',
 'legs', '{glutes}', 'squat',
 'compound', 'machine', 'pemula', true,
 ARRAY['Posisikan bar smith di punggung atas, kaki sedikit di depan badan.','Lepas kunci bar, turun jongkok terkontrol.','Turun hingga paha sejajar lantai.','Dorong kembali ke atas dan kunci bar setelah selesai.'],
 '{lutut,punggung_bawah}', 'squat', 'https://www.youtube.com/watch?v=fEuYM-miK5U'),
('zercher-squat', 'Zercher Squat', 'Zercher Squat',
 'legs', '{core,arms}', 'squat',
 'compound', 'barbell', 'mahir', true,
 ARRAY['Pegang bar di lipatan siku, dekap di depan tubuh.','Kaki selebar bahu, dada tegak.','Turun jongkok dalam menjaga torso tegak.','Dorong berdiri kembali, siku tetap terangkat.'],
 '{punggung_bawah,siku}', 'squat', 'https://www.youtube.com/watch?v=IWofyrgYKh4'),
('good-morning', 'Good Morning', 'Good Morning',
 'legs', '{back,glutes}', 'hinge',
 'compound', 'barbell', 'menengah', true,
 ARRAY['Bar di punggung atas, kaki selebar pinggul, lutut sedikit menekuk.','Dorong pinggul ke belakang menurunkan dada ke depan.','Turun hingga torso hampir sejajar lantai, punggung netral.','Dorong pinggul ke depan untuk kembali tegak.'],
 '{punggung_bawah}', 'hinge', 'https://www.youtube.com/watch?v=7cpldMZjLOs'),
('trap-bar-deadlift', 'Trap Bar Deadlift', 'Deadlift Trap Bar',
 'legs', '{glutes,back,core}', 'hinge',
 'compound', 'barbell', 'menengah', true,
 ARRAY['Berdiri di tengah trap bar, kaki selebar pinggul.','Tekuk pinggul dan lutut, genggam pegangan di kedua sisi.','Dorong lantai hingga berdiri tegak, punggung netral.','Turunkan terkontrol dengan pola hinge.'],
 '{punggung_bawah}', 'hinge', 'https://www.youtube.com/watch?v=EsqwERaSTMI'),
('cable-pull-through', 'Cable Pull Through', 'Cable Pull Through',
 'legs', '{glutes,back}', 'hinge',
 'compound', 'machine', 'pemula', true,
 ARRAY['Membelakangi katrol rendah, pegang tali di antara kaki.','Melangkah maju, pinggul menekuk, punggung netral.','Dorong pinggul ke depan hingga berdiri tegak, remas glutes.','Kembalikan terkontrol dengan pola hinge.'],
 '{punggung_bawah}', 'hinge', 'https://www.youtube.com/watch?v=DbSF7ipBh5Y'),
('back-extension', 'Back Extension', 'Back Extension',
 'back', '{glutes,legs}', 'hinge',
 'compound', 'bodyweight', 'pemula', true,
 ARRAY['Posisikan paha di bantalan bangku hyperextension.','Turunkan torso ke bawah terkontrol.','Angkat torso hingga sejajar garis tubuh, jangan hiperekstensi berlebihan.','Remas glutes dan punggung bawah di puncak.'],
 '{punggung_bawah}', 'hinge', 'https://www.youtube.com/watch?v=H8Swl1N-uis'),
('nordic-hamstring-curl', 'Nordic Hamstring Curl', 'Nordic Hamstring Curl',
 'legs', '{core}', 'isolation_legs',
 'isolation', 'bodyweight', 'mahir', false,
 ARRAY['Berlutut dengan pergelangan kaki ditahan atau dikaitkan.','Jaga tubuh lurus dari lutut ke kepala.','Turunkan tubuh ke depan selambat mungkin dengan hamstring.','Gunakan tangan menahan di lantai lalu dorong kembali.'],
 '{lutut}', 'isolation_legs', 'https://www.youtube.com/watch?v=3-4pKUhkzoQ'),
('single-leg-hip-thrust', 'Single Leg Hip Thrust', 'Hip Thrust Satu Kaki',
 'legs', '{glutes,core}', 'hinge',
 'compound', 'bodyweight', 'menengah', true,
 ARRAY['Punggung atas bersandar di bangku, satu kaki menapak.','Kaki lainnya terangkat lurus.','Dorong pinggul ke atas dengan satu kaki hingga badan sejajar.','Turunkan terkontrol tanpa memutar pinggul.'],
 '{punggung_bawah}', 'hinge', 'https://www.youtube.com/watch?v=qCObDXTe4KY'),
('close-grip-bench-press', 'Close Grip Bench Press', 'Bench Press Grip Rapat',
 'arms', '{chest,shoulders}', 'push_horizontal',
 'compound', 'barbell', 'menengah', true,
 ARRAY['Berbaring di bangku, genggam bar selebar bahu atau sedikit lebih sempit.','Turunkan bar ke dada bawah, siku dekat tubuh.','Dorong bar ke atas hingga lengan lurus.','Fokus pada trisep sepanjang gerakan.'],
 '{siku,bahu,pergelangan_tangan}', 'push_horizontal', 'https://www.youtube.com/watch?v=vEUyEOVn3yM'),
('incline-barbell-bench-press', 'Incline Barbell Bench Press', 'Incline Bench Press Barbel',
 'chest', '{shoulders,arms}', 'push_horizontal',
 'compound', 'barbell', 'menengah', true,
 ARRAY['Atur bangku miring sekitar 30 derajat.','Genggam bar sedikit lebih lebar dari bahu.','Turunkan bar ke dada atas terkontrol.','Dorong kembali ke atas hingga lengan lurus.'],
 '{bahu}', 'push_horizontal', 'https://www.youtube.com/watch?v=SrqOu55lrYU'),
('knee-push-up', 'Knee Push-Up', 'Push-Up Lutut',
 'chest', '{arms,shoulders,core}', 'push_horizontal',
 'compound', 'bodyweight', 'pemula', true,
 ARRAY['Posisi push-up dengan lutut menapak lantai.','Tubuh lurus dari lutut ke kepala.','Turunkan dada mendekati lantai.','Dorong kembali ke atas.'],
 '{pergelangan_tangan}', 'push_horizontal', 'https://www.youtube.com/watch?v=lFR1GWy1Dcs'),
('archer-push-up', 'Archer Push-Up', 'Archer Push-Up',
 'chest', '{arms,shoulders,core}', 'push_horizontal',
 'compound', 'bodyweight', 'mahir', true,
 ARRAY['Posisi push-up dengan tangan lebih lebar dari bahu.','Turunkan tubuh condong ke satu sisi, lengan sisi itu menekuk.','Lengan sisi lain tetap hampir lurus.','Dorong kembali ke tengah dan ganti sisi.'],
 '{bahu,pergelangan_tangan}', 'push_horizontal', 'https://www.youtube.com/watch?v=mzr0RYNDzzI'),
('plyometric-push-up', 'Plyometric Push-Up', 'Push-Up Plyometrik',
 'chest', '{arms,shoulders,core}', 'push_horizontal',
 'compound', 'bodyweight', 'mahir', true,
 ARRAY['Mulai posisi push-up standar.','Turunkan dada lalu dorong eksplosif hingga telapak lepas dari lantai.','Opsional tepuk tangan di udara.','Mendarat lembut dengan siku sedikit menekuk.'],
 '{pergelangan_tangan,bahu}', 'push_horizontal', 'https://www.youtube.com/watch?v=g3SKjjgHvFM'),
('decline-push-up', 'Decline Push-Up', 'Push-Up Decline',
 'chest', '{shoulders,arms,core}', 'push_horizontal',
 'compound', 'bodyweight', 'menengah', true,
 ARRAY['Kaki di atas bangku, tangan di lantai selebar bahu.','Tubuh lurus dari tumit ke kepala.','Turunkan dada mendekati lantai.','Dorong kembali hingga lengan lurus.'],
 '{bahu,pergelangan_tangan}', 'push_horizontal', 'https://www.youtube.com/watch?v=5QFjmotLfW4'),
('push-press', 'Push Press', 'Push Press',
 'shoulders', '{legs,arms,core}', 'push_vertical',
 'compound', 'barbell', 'mahir', true,
 ARRAY['Bar di depan bahu, kaki selebar pinggul.','Tekuk lutut sedikit lalu dorong eksplosif dengan kaki.','Gunakan momentum untuk mendorong bar ke atas kepala.','Kunci lengan di atas lalu turunkan terkontrol.'],
 '{bahu,punggung_bawah}', 'push_vertical', 'https://www.youtube.com/watch?v=HKx22sWywxc'),
('handstand-push-up', 'Handstand Push-Up', 'Push-Up Handstand',
 'shoulders', '{arms,core}', 'push_vertical',
 'compound', 'bodyweight', 'mahir', true,
 ARRAY['Handstand menghadap dinding sebagai penyangga.','Turunkan kepala terkontrol mendekati lantai.','Dorong kembali hingga lengan lurus.','Jaga inti dan glutes aktif agar tubuh lurus.'],
 '{bahu,pergelangan_tangan}', 'push_vertical', 'https://www.youtube.com/watch?v=oTy2ORF_NC4'),
('landmine-press', 'Landmine Press', 'Landmine Press',
 'shoulders', '{chest,core,arms}', 'push_vertical',
 'compound', 'barbell', 'menengah', true,
 ARRAY['Satu ujung bar di landmine, pegang ujung lain setinggi bahu.','Berdiri kaki selebar bahu, inti aktif.','Dorong bar ke atas-depan hingga lengan lurus.','Turunkan terkontrol ke bahu.'],
 '{bahu}', 'push_vertical', 'https://www.youtube.com/watch?v=qFXojXa-RCU'),
('assisted-pull-up', 'Assisted Pull-Up', 'Pull-Up Berbantuan',
 'back', '{arms}', 'pull_vertical',
 'compound', 'machine', 'pemula', true,
 ARRAY['Berlutut di bantalan mesin assisted pull-up.','Genggam palang selebar bahu.','Tarik tubuh ke atas hingga dagu melewati palang.','Turun terkontrol hingga lengan lurus.'],
 '{bahu}', 'pull_vertical', 'https://www.youtube.com/watch?v=gx0RWT7WbmA'),
('muscle-up', 'Muscle-Up', 'Muscle-Up',
 'back', '{arms,chest,core}', 'pull_vertical',
 'compound', 'bodyweight', 'mahir', true,
 ARRAY['Gantung di palang dengan grip sedikit lebih lebar dari bahu.','Tarik eksplosif membawa dada ke atas palang.','Transisi siku ke atas lalu dorong hingga lengan lurus.','Turun terkontrol kembali ke posisi gantung.'],
 '{bahu,siku,pergelangan_tangan}', 'pull_vertical', 'https://www.youtube.com/watch?v=FEX27prBhO0'),
('chest-supported-row', 'Chest Supported Row', 'Row Dada Tersangga',
 'back', '{arms,shoulders}', 'pull_horizontal',
 'compound', 'dumbbell', 'menengah', true,
 ARRAY['Telungkup di bangku miring, dada tersangga.','Pegang dumbbell menggantung lurus.','Tarik dumbbell ke arah pinggul, remas tulang belikat.','Turunkan terkontrol tanpa mengayun.'],
 '{bahu}', 'pull_horizontal', 'https://www.youtube.com/watch?v=vmX58YYK3-8'),
('pendlay-row', 'Pendlay Row', 'Pendlay Row',
 'back', '{arms,core}', 'pull_horizontal',
 'compound', 'barbell', 'mahir', true,
 ARRAY['Bar di lantai, torso sejajar lantai, punggung netral.','Genggam bar sedikit lebih lebar dari bahu.','Tarik bar eksplosif ke dada bawah.','Kembalikan bar ke lantai setiap repetisi.'],
 '{punggung_bawah}', 'pull_horizontal', 'https://www.youtube.com/watch?v=axoeDmW0oAY'),
('straight-arm-pulldown', 'Straight Arm Pulldown', 'Straight Arm Pulldown',
 'back', '{core}', 'isolation_back',
 'isolation', 'machine', 'menengah', false,
 ARRAY['Berdiri menghadap katrol tinggi, lengan lurus memegang bar.','Condong sedikit ke depan, inti aktif.','Tarik bar ke bawah ke arah paha dengan lengan tetap lurus.','Kembalikan terkontrol merasakan regangan lat.'],
 '{bahu}', 'isolation_back', 'https://www.youtube.com/watch?v=G9uNaXGTJ4w'),
('reverse-pec-deck', 'Reverse Pec Deck', 'Reverse Pec Deck',
 'shoulders', '{back}', 'isolation_back',
 'isolation', 'machine', 'pemula', false,
 ARRAY['Duduk menghadap sandaran mesin pec deck.','Pegang pegangan di depan setinggi bahu.','Buka lengan ke belakang hingga sejajar bahu.','Kembalikan terkontrol tanpa memantul.'],
 '{bahu}', 'isolation_back', 'https://www.youtube.com/watch?v=dC7jhEk-29A'),
('preacher-curl', 'Preacher Curl', 'Preacher Curl',
 'arms', '{}', 'isolation_biceps',
 'isolation', 'machine', 'pemula', false,
 ARRAY['Duduk di bangku preacher, lengan atas menempel bantalan.','Pegang bar atau pegangan mesin.','Tekuk siku mengangkat beban, remas bisep.','Turunkan terkontrol hampir lurus penuh.'],
 '{siku}', 'isolation_biceps', 'https://www.youtube.com/watch?v=vngli9UR6Hw'),
('incline-dumbbell-curl', 'Incline Dumbbell Curl', 'Curl Dumbbell Incline',
 'arms', '{}', 'isolation_biceps',
 'isolation', 'dumbbell', 'menengah', false,
 ARRAY['Duduk di bangku miring 45-60 derajat, lengan menggantung.','Telapak menghadap depan.','Tekuk siku mengangkat dumbbell tanpa mengayun bahu.','Turunkan terkontrol merasakan regangan bisep.'],
 '{siku,bahu}', 'isolation_biceps', 'https://www.youtube.com/watch?v=DCe8f6vMe9A'),
('concentration-curl', 'Concentration Curl', 'Concentration Curl',
 'arms', '{}', 'isolation_biceps',
 'isolation', 'dumbbell', 'pemula', false,
 ARRAY['Duduk, siku menempel sisi dalam paha.','Pegang dumbbell menggantung lurus.','Tekuk siku mengangkat dumbbell ke arah bahu.','Turunkan terkontrol tanpa menggerakkan lengan atas.'],
 '{siku}', 'isolation_biceps', 'https://www.youtube.com/watch?v=4tqc6FQSHn8'),
('cable-bicep-curl', 'Cable Bicep Curl', 'Curl Bisep Kabel',
 'arms', '{}', 'isolation_biceps',
 'isolation', 'machine', 'pemula', false,
 ARRAY['Berdiri menghadap katrol rendah, pegang bar.','Siku menempel di sisi tubuh.','Tekuk siku mengangkat bar ke arah dada.','Turunkan terkontrol menjaga tegangan kabel.'],
 '{siku}', 'isolation_biceps', 'https://www.youtube.com/watch?v=2MUEL4nL6hA'),
('dumbbell-kickback', 'Dumbbell Kickback', 'Kickback Dumbbell',
 'arms', '{}', 'isolation_triceps',
 'isolation', 'dumbbell', 'pemula', false,
 ARRAY['Condongkan badan ke depan, punggung netral.','Lengan atas sejajar lantai, siku menekuk 90 derajat.','Luruskan lengan ke belakang, remas trisep.','Kembalikan terkontrol tanpa menggerakkan lengan atas.'],
 '{siku}', 'isolation_triceps', 'https://www.youtube.com/watch?v=m9me06UBPKc'),
('diamond-push-up', 'Diamond Push-Up', 'Push-Up Diamond',
 'arms', '{chest,shoulders,core}', 'isolation_triceps',
 'isolation', 'bodyweight', 'menengah', false,
 ARRAY['Posisi push-up dengan ibu jari dan telunjuk membentuk segitiga.','Tubuh lurus, inti aktif.','Turunkan dada ke arah tangan, siku dekat tubuh.','Dorong kembali fokus pada trisep.'],
 '{pergelangan_tangan,siku}', 'isolation_triceps', 'https://www.youtube.com/watch?v=kGhDnFwMY3E'),
('pec-deck-fly', 'Pec Deck Fly', 'Pec Deck Fly',
 'chest', '{shoulders}', 'isolation_chest',
 'isolation', 'machine', 'pemula', false,
 ARRAY['Duduk dengan punggung menempel sandaran.','Pegang pegangan setinggi dada, siku sedikit menekuk.','Bawa kedua pegangan bertemu di depan dada.','Kembalikan terkontrol merasakan regangan dada.'],
 '{bahu}', 'isolation_chest', 'https://www.youtube.com/watch?v=3jYo5cMU3d4'),
('lateral-lunge', 'Lateral Lunge', 'Lunge Samping',
 'legs', '{glutes}', 'isolation_legs',
 'compound', 'bodyweight', 'menengah', true,
 ARRAY['Berdiri tegak, melangkah lebar ke samping.','Tekuk lutut kaki yang melangkah, kaki lain lurus.','Dorong pinggul ke belakang, dada tegak.','Dorong kembali ke posisi awal dan ganti sisi.'],
 '{lutut}', 'isolation_legs', 'https://www.youtube.com/watch?v=21s1CisV3jU'),
('curtsy-lunge', 'Curtsy Lunge', 'Curtsy Lunge',
 'legs', '{glutes}', 'isolation_legs',
 'compound', 'bodyweight', 'menengah', true,
 ARRAY['Berdiri tegak, melangkah satu kaki menyilang ke belakang.','Tekuk kedua lutut turun terkontrol.','Jaga dada tegak dan pinggul menghadap depan.','Dorong kembali berdiri dan ganti sisi.'],
 '{lutut}', 'isolation_legs', 'https://www.youtube.com/watch?v=g8mCJDtD2DQ'),
('jump-lunge', 'Jump Lunge', 'Lunge Lompat',
 'legs', '{glutes,core}', 'isolation_legs',
 'compound', 'bodyweight', 'mahir', true,
 ARRAY['Mulai posisi lunge, kedua lutut menekuk.','Lompat eksplosif ke atas.','Ganti posisi kaki di udara.','Mendarat lembut langsung ke lunge sisi lain.'],
 '{lutut,pergelangan_kaki}', 'isolation_legs', 'https://www.youtube.com/watch?v=iJMsF7fzrOM'),
('hip-adduction-machine', 'Hip Adduction Machine', 'Hip Adduction Mesin',
 'legs', '{}', 'isolation_legs',
 'isolation', 'machine', 'pemula', false,
 ARRAY['Duduk di mesin, sisi dalam paha menempel bantalan.','Mulai dengan kaki terbuka.','Rapatkan kedua kaki melawan tahanan.','Kembalikan terkontrol.'],
 '{}', 'isolation_legs', 'https://www.youtube.com/watch?v=OjI5OpV6IWA'),
('seated-leg-curl', 'Seated Leg Curl', 'Seated Leg Curl',
 'legs', '{}', 'isolation_legs',
 'isolation', 'machine', 'pemula', false,
 ARRAY['Duduk di mesin, bantalan di atas betis bawah.','Punggung menempel sandaran.','Tekuk lutut menarik bantalan ke bawah-belakang.','Kembalikan terkontrol.'],
 '{lutut}', 'isolation_legs', 'https://www.youtube.com/watch?v=t9sTSr-JYSs'),
('sissy-squat', 'Sissy Squat', 'Sissy Squat',
 'legs', '{core}', 'isolation_legs',
 'isolation', 'bodyweight', 'mahir', false,
 ARRAY['Berdiri, pegang penyangga bila perlu.','Condongkan tubuh ke belakang sambil menekuk lutut.','Lutut bergerak ke depan, tumit terangkat.','Kembali berdiri dengan kontraksi paha depan.'],
 '{lutut}', 'isolation_legs', 'https://www.youtube.com/watch?v=AYN-U5nZieY'),
('standing-calf-raise-machine', 'Standing Calf Raise Machine', 'Standing Calf Raise Mesin',
 'legs', '{}', 'calf',
 'isolation', 'machine', 'pemula', false,
 ARRAY['Bahu di bawah bantalan mesin, ujung kaki di pijakan.','Turunkan tumit hingga regangan betis.','Angkat tumit setinggi mungkin.','Turunkan terkontrol.'],
 '{pergelangan_kaki}', 'calf', 'https://www.youtube.com/watch?v=SVtg-1loH4c'),
('single-leg-calf-raise', 'Single Leg Calf Raise', 'Calf Raise Satu Kaki',
 'legs', '{}', 'calf',
 'isolation', 'bodyweight', 'menengah', false,
 ARRAY['Berdiri satu kaki di tepi pijakan, tumit menggantung.','Pegang penyangga untuk keseimbangan.','Angkat tumit setinggi mungkin.','Turunkan perlahan hingga regangan penuh.'],
 '{pergelangan_kaki}', 'calf', 'https://www.youtube.com/watch?v=ElcvJ0kjt6c'),
('crunch', 'Crunch', 'Crunch',
 'core', '{}', 'core',
 'isolation', 'bodyweight', 'pemula', false,
 ARRAY['Berbaring, lutut menekuk, tangan di samping kepala.','Angkat bahu dari lantai dengan otot perut.','Jangan menarik leher.','Turunkan terkontrol.'],
 '{}', 'core', 'https://www.youtube.com/watch?v=_M2Etme-tfE'),
('bicycle-crunch', 'Bicycle Crunch', 'Bicycle Crunch',
 'core', '{}', 'core',
 'isolation', 'bodyweight', 'pemula', false,
 ARRAY['Berbaring, tangan di samping kepala, kaki terangkat.','Bawa siku ke lutut berlawanan sambil meluruskan kaki lain.','Bergantian sisi dengan ritme terkontrol.','Jaga punggung bawah menempel lantai.'],
 '{punggung_bawah}', 'core', 'https://www.youtube.com/watch?v=eqg47ZuGZXQ'),
('russian-twist', 'Russian Twist', 'Russian Twist',
 'core', '{}', 'core',
 'isolation', 'bodyweight', 'pemula', false,
 ARRAY['Duduk, lutut menekuk, condong sedikit ke belakang.','Angkat kaki bila mampu.','Putar torso ke kiri dan kanan bergantian.','Gerakan dari inti, bukan lengan.'],
 '{punggung_bawah}', 'core', 'https://www.youtube.com/watch?v=wkD8rjkodUI'),
('hanging-knee-raise', 'Hanging Knee Raise', 'Hanging Knee Raise',
 'core', '{arms}', 'core',
 'isolation', 'bodyweight', 'menengah', false,
 ARRAY['Gantung di palang, lengan lurus.','Tarik lutut ke arah dada terkontrol.','Hindari mengayun badan.','Turunkan kaki perlahan.'],
 '{bahu}', 'core', 'https://www.youtube.com/watch?v=4BbN9x_GBzY'),
('hanging-leg-raise', 'Hanging Leg Raise', 'Hanging Leg Raise',
 'core', '{arms}', 'core',
 'isolation', 'bodyweight', 'mahir', false,
 ARRAY['Gantung di palang, kaki lurus.','Angkat kedua kaki lurus hingga sejajar pinggul atau lebih.','Kontrol tanpa ayunan.','Turunkan perlahan.'],
 '{bahu,punggung_bawah}', 'core', 'https://www.youtube.com/watch?v=Pr1ieGZ5atk'),
('hollow-body-hold', 'Hollow Body Hold', 'Hollow Body Hold',
 'core', '{}', 'core',
 'isolation', 'bodyweight', 'menengah', false,
 ARRAY['Berbaring, punggung bawah ditekan ke lantai.','Angkat bahu dan kaki dari lantai.','Lengan lurus di samping telinga.','Tahan posisi dengan inti aktif.'],
 '{punggung_bawah}', 'core', 'https://www.youtube.com/watch?v=Xk-JcNj6lfY'),
('v-up', 'V-Up', 'V-Up',
 'core', '{}', 'core',
 'isolation', 'bodyweight', 'menengah', false,
 ARRAY['Berbaring lurus, lengan di atas kepala.','Angkat kaki dan torso bersamaan membentuk huruf V.','Sentuh ujung kaki di puncak.','Turunkan terkontrol.'],
 '{punggung_bawah}', 'core', 'https://www.youtube.com/watch?v=oirraQEz-74'),
('ab-wheel-rollout', 'Ab Wheel Rollout', 'Ab Wheel Rollout',
 'core', '{shoulders,back}', 'core',
 'isolation', 'bodyweight', 'menengah', false,
 ARRAY['Berlutut memegang ab wheel di lantai.','Gulirkan roda ke depan perlahan, tubuh memanjang.','Jaga punggung tidak melengkung turun.','Tarik kembali dengan otot inti.'],
 '{punggung_bawah,bahu}', 'core', 'https://www.youtube.com/watch?v=uYBOBBv9GzY'),
('dragon-flag', 'Dragon Flag', 'Dragon Flag',
 'core', '{back}', 'core',
 'isolation', 'bodyweight', 'mahir', false,
 ARRAY['Berbaring, pegang bangku di belakang kepala.','Angkat seluruh tubuh lurus bertumpu pada bahu.','Turunkan tubuh perlahan tanpa menekuk pinggul.','Jaga tubuh tetap segaris sepanjang gerakan.'],
 '{punggung_bawah,bahu}', 'core', 'https://www.youtube.com/watch?v=At0mMAHqWrQ'),
('pallof-press', 'Pallof Press', 'Pallof Press',
 'core', '{shoulders}', 'core',
 'isolation', 'machine', 'pemula', false,
 ARRAY['Berdiri menyamping dari katrol setinggi dada.','Pegang gagang dengan dua tangan di depan dada.','Dorong lengan lurus ke depan melawan tarikan rotasi.','Tahan lalu kembalikan terkontrol.'],
 '{}', 'core', 'https://www.youtube.com/watch?v=nFspBRHke4w'),
('cable-woodchop', 'Cable Woodchop', 'Cable Woodchop',
 'core', '{shoulders}', 'core',
 'isolation', 'machine', 'menengah', false,
 ARRAY['Berdiri menyamping dari katrol tinggi.','Pegang gagang dengan dua tangan.','Tarik diagonal dari atas ke pinggul berlawanan dengan rotasi torso.','Kembalikan terkontrol dan ganti sisi.'],
 '{punggung_bawah}', 'core', 'https://www.youtube.com/watch?v=pAplQXk3dkU'),
('l-sit', 'L-Sit', 'L-Sit',
 'core', '{arms,shoulders}', 'core',
 'isolation', 'bodyweight', 'mahir', false,
 ARRAY['Duduk di antara paralel bar atau lantai, telapak menekan.','Angkat tubuh, kaki lurus ke depan membentuk L.','Bahu ditekan ke bawah, lengan lurus.','Tahan selama durasi target.'],
 '{bahu,pergelangan_tangan}', 'core', 'https://www.youtube.com/watch?v=HxDP7SqggpI'),
('turkish-get-up', 'Turkish Get-Up', 'Turkish Get-Up',
 'full_body', '{core,shoulders,legs}', 'core',
 'compound', 'dumbbell', 'mahir', true,
 ARRAY['Berbaring memegang beban lurus di atas satu lengan.','Bangun bertahap: siku, tangan, lutut, hingga berdiri.','Mata mengawasi beban sepanjang gerakan.','Turun kembali dengan urutan terbalik terkontrol.'],
 '{bahu,punggung_bawah}', 'core', 'https://www.youtube.com/watch?v=lpltjWHd0ek'),
('farmer-carry', 'Farmer Carry', 'Farmer Carry',
 'full_body', '{core,back,arms}', 'core',
 'compound', 'dumbbell', 'pemula', true,
 ARRAY['Pegang beban berat di kedua tangan di samping tubuh.','Berdiri tegak, bahu ke belakang, inti aktif.','Berjalan dengan langkah stabil dan postur tegak.','Jaga beban tidak menyentuh tubuh.'],
 '{punggung_bawah}', 'core', 'https://www.youtube.com/watch?v=lLAw6fUccKA'),
('treadmill-run', 'Treadmill Run', 'Lari Treadmill',
 'legs', '{}', 'cardio',
 'cardio', 'cardio', 'pemula', false,
 ARRAY['Mulai dengan jalan cepat sebagai pemanasan.','Naikkan kecepatan bertahap ke pace lari nyaman.','Postur tegak, pandangan ke depan, lengan mengayun rileks.','Turunkan kecepatan bertahap untuk pendinginan.'],
 '{lutut,pergelangan_kaki}', 'cardio', 'https://www.youtube.com/watch?v=K6I24WgiiPw'),
('stair-climber', 'Stair Climber', 'Mesin Tangga',
 'legs', '{glutes}', 'cardio',
 'cardio', 'cardio', 'pemula', false,
 ARRAY['Berdiri tegak di mesin, pegang rel dengan ringan.','Melangkah dengan telapak penuh setiap anak tangga.','Jangan menumpukan berat badan ke rel.','Jaga irama stabil sesuai intensitas target.'],
 '{lutut}', 'cardio', 'https://www.youtube.com/watch?v=ww3YV_N6U_U'),
('high-knees', 'High Knees', 'High Knees',
 'full_body', '{legs,core}', 'cardio',
 'cardio', 'bodyweight', 'pemula', false,
 ARRAY['Berdiri tegak, lari di tempat.','Angkat lutut setinggi pinggul bergantian cepat.','Ayunkan lengan berlawanan seperti berlari.','Mendarat lembut di ujung kaki.'],
 '{lutut,pergelangan_kaki}', 'cardio', 'https://www.youtube.com/watch?v=oDdkytliOqE'),
('assault-bike', 'Assault Bike', 'Assault Bike',
 'full_body', '{legs,arms}', 'cardio',
 'cardio', 'cardio', 'menengah', false,
 ARRAY['Atur sadel setinggi pinggul, duduk tegak.','Kayuh sambil mendorong-menarik pegangan.','Sinkronkan gerakan lengan dan kaki.','Atur intensitas sesuai program interval atau steady.'],
 '{}', 'cardio', 'https://www.youtube.com/watch?v=KC-ZSfOmXgE'),
('box-jump', 'Box Jump', 'Box Jump',
 'legs', '{glutes,core}', 'squat',
 'compound', 'bodyweight', 'menengah', true,
 ARRAY['Berdiri menghadap box stabil.','Tekuk lutut lalu lompat eksplosif ke atas box.','Mendarat lembut dengan kedua kaki penuh di box.','Berdiri tegak lalu turun melangkah, bukan melompat.'],
 '{lutut,pergelangan_kaki}', 'squat', 'https://www.youtube.com/watch?v=LeiLzSU3OXE'),
('shadow-boxing', 'Shadow Boxing', 'Shadow Boxing',
 'full_body', '{shoulders,core,arms}', 'cardio',
 'cardio', 'bodyweight', 'pemula', false,
 ARRAY['Kuda-kuda boxing, tangan di depan wajah.','Lempar kombinasi pukulan ke udara: jab, cross, hook.','Bergerak kaki ringan sambil menjaga guard.','Pertahankan intensitas selama ronde target.'],
 '{bahu}', 'cardio', 'https://www.youtube.com/watch?v=KidSVNv0WcY'),
('thruster', 'Thruster', 'Thruster',
 'full_body', '{legs,shoulders,core}', 'squat',
 'compound', 'barbell', 'mahir', true,
 ARRAY['Bar di depan bahu posisi front squat.','Turun jongkok penuh terkontrol.','Berdiri eksplosif sambil mendorong bar ke atas kepala.','Turunkan bar ke bahu dan ulangi mengalir.'],
 '{bahu,lutut,punggung_bawah}', 'squat', 'https://www.youtube.com/watch?v=Zvt5-mugUco'),
('dumbbell-snatch', 'Dumbbell Snatch', 'Snatch Dumbbell',
 'full_body', '{legs,shoulders,back,core}', 'hinge',
 'compound', 'dumbbell', 'mahir', true,
 ARRAY['Dumbbell di lantai di antara kaki, pola hinge.','Tarik eksplosif dengan dorongan pinggul.','Bawa dumbbell lurus ke atas kepala dalam satu gerakan.','Turunkan terkontrol dan ganti tangan.'],
 '{punggung_bawah,bahu}', 'hinge', 'https://www.youtube.com/watch?v=0yd9443Y-fg'),
('sprint-interval', 'Sprint Interval', 'Interval Sprint',
 'full_body', '{legs}', 'cardio',
 'cardio', 'cardio', 'mahir', false,
 ARRAY['Pemanasan jalan-jogging 5 menit.','Sprint intensitas tinggi 20-30 detik.','Pulih jalan atau jogging ringan 60-90 detik.','Ulangi 6-10 ronde lalu pendinginan.'],
 '{lutut,pergelangan_kaki}', 'cardio', 'https://www.youtube.com/watch?v=2m_4dwouElQ')

on conflict (slug) do nothing;
